basePath: /
definitions:
  handlers.userResponse:
    properties:
      email:
        type: string
      name:
        type: string
      surname:
        type: string
      user_type:
        type: string
      uuid:
        type: string
    type: object
  models.ApiError:
    properties:
      error:
        type: string
    type: object
  models.Lesson:
    properties:
      created_at:
        type: string
      description:
        type: string
      duration_sec:
        type: integer
      id:
        type: integer
      interest:
        type: string
      is_published:
        type: boolean
      level:
        type: string
      order:
        type: integer
      subject_id:
        description: under question
        type: integer
      target_age_max:
        type: integer
      target_age_min:
        type: integer
      title:
        type: string
      updated_at:
        type: string
      video_data:
        items:
          type: integer
        type: array
      video_filename:
        type: string
      video_mime_type:
        type: string
    type: object
  models.Subject:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open.api/
host: api.ozinshe.com
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: this is a Educational Application project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: EdTech API
  version: "1.0"
paths:
  /lessons:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Lesson'
            type: array
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Find all lessons
      tags:
      - lessons
    post:
      consumes:
      - application/json
      parameters:
      - description: Lesson_title
        in: query
        name: title
        required: true
        type: string
      - description: Lesson_description
        in: query
        name: description
        required: true
        type: string
      - description: Lesson_subject_id
        in: query
        name: subject_id
        required: true
        type: integer
      - description: Topic_order
        in: query
        name: order
        required: true
        type: integer
      - description: Lessons_level
        in: query
        name: level
        required: true
        type: string
      - description: Lessons_interest
        in: query
        name: interest
        required: true
        type: string
      - description: minimum age for viewing lesson
        in: query
        name: target_age_min
        required: true
        type: integer
      - description: maximum age for viewing lesson
        in: query
        name: target_age_max
        required: true
        type: integer
      - description: Lessons_video
        in: query
        name: video_data
        required: true
        type: string
      - description: Lessons_video_filename
        in: query
        name: video_filename
        required: true
        type: string
      - description: Lessons_video_MIME-type
        in: query
        name: video_mime_type
        required: true
        type: string
      - description: Lessons_video_duration_seconds
        in: query
        name: duration_sec
        required: true
        type: string
      - description: lessons_video_is_published
        in: query
        name: is_published
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              id:
                type: integer
            type: object
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Create Lesson
      tags:
      - lessons
  /lessons/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Lesson_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: delete lesson by id
      tags:
      - lessons
    get:
      consumes:
      - application/json
      parameters:
      - description: Lesson_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Lesson'
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: find lesson by id
      tags:
      - lessons
    put:
      consumes:
      - application/json
      parameters:
      - description: Lesson_id
        in: path
        name: id
        required: true
        type: integer
      - description: Lesson_title
        in: query
        name: title
        required: true
        type: string
      - description: Lesson_description
        in: query
        name: description
        required: true
        type: string
      - description: Lesson_subject_id
        in: query
        name: subject_id
        required: true
        type: integer
      - description: Topic_order
        in: query
        name: order
        required: true
        type: integer
      - description: Lessons_level
        in: query
        name: level
        required: true
        type: string
      - description: Lessons_interest
        in: query
        name: interest
        required: true
        type: string
      - description: minimum age for viewing lesson
        in: query
        name: target_age_min
        required: true
        type: integer
      - description: maximum age for viewing lesson
        in: query
        name: target_age_max
        required: true
        type: integer
      - description: Lessons_video
        in: query
        name: video_data
        required: true
        type: string
      - description: Lessons_video_filename
        in: query
        name: video_filename
        required: true
        type: string
      - description: Lessons_video_MIME-type
        in: query
        name: video_mime_type
        required: true
        type: string
      - description: Lessons_video_duration_seconds
        in: query
        name: duration_sec
        required: true
        type: string
      - description: lessons_video_is_published
        in: query
        name: is_published
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              id:
                type: integer
            type: object
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Update Lesson
      tags:
      - lessons
  /subjects:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Subject'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: find all subjects
      tags:
      - subjects
  /subjects/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Subject_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: delete subject by id
      tags:
      - subjects
    get:
      consumes:
      - application/json
      parameters:
      - description: Subject_id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Subject'
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: find subject by id
      tags:
      - subjects
    post:
      consumes:
      - application/json
      parameters:
      - description: Subject_title
        in: query
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              id:
                type: integer
            type: object
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: create subject
      tags:
      - subjects
    put:
      consumes:
      - application/json
      parameters:
      - description: Subject_title
        in: query
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: update subject
      tags:
      - subjects
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.userResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Get All Users
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: User_Name
        in: query
        name: name
        required: true
        type: string
      - description: User_Surname
        in: query
        name: surname
        required: true
        type: string
      - description: Email
        in: query
        name: email
        required: true
        type: string
      - description: User_Type
        in: query
        name: type
        required: true
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              uuid:
                type: string
            type: object
        "400":
          description: Invalid Payload
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Create User
      tags:
      - users
  /users/{uuid}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid user uuid
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Delete User
      tags:
      - users
    get:
      consumes:
      - application/json
      parameters:
      - description: User UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.userResponse'
        "400":
          description: Invalid user uuid
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      security:
      - Bearer: []
      summary: Find By Id
      tags:
      - users
    put:
      consumes:
      - application/json
      parameters:
      - description: User UUID
        in: path
        name: uuid
        required: true
        type: string
      - description: User Name
        in: query
        name: name
        required: true
        type: string
      - description: User Surname
        in: query
        name: surname
        required: true
        type: string
      - description: Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid user uuid
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Update User
      tags:
      - users
  /users/{uuid}/activate:
    patch:
      consumes:
      - application/json
      parameters:
      - description: User UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid user uuid
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: set user status to active
      tags:
      - users
  /users/{uuid}/changePassword:
    patch:
      consumes:
      - application/json
      parameters:
      - description: User UUID
        in: path
        name: uuid
        required: true
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid user uuid
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: ChangePassword User
      tags:
      - users
  /users/{uuid}/deactivate:
    patch:
      consumes:
      - application/json
      parameters:
      - description: User UUID
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid user uuid
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: set user status to inactive
      tags:
      - users
swagger: "2.0"
